### ISSUE TITLE
The vEdge on KVM (EVE-NG) lost configuration or unable to communicate with VCO after the Shutdown/PowerOff the VCE

### ISSUE THREAD

**Issue by xiaurrehman143** [iddocohen/vce_cloudinit#2]
I have successfully initiated the Virtual VeloCloud Edge on KVM (EVE-NG). The vEdge is provisioned to the VCO. But the edge lost configuration or is unable to communicate with VCO after Turn off or shut down the vEdge. After Power ON the vEdge, the vEdge boot is in the factory default setting.

**Comment by iddocohen** [comment]
Hi @xiaurrehman143,

you state "...the vEdge is provisioned to the VCO. But the edge lost configuration or is unable to communicate with VCO...".

What I would like to understand, did the VCE got activated against that the VCO or did it never reach the VCO at the first place? Why I ask is, the cloud-init configuration is used only at activation time. As soon as the VCO takes "control" over the VCE, the configuration gets pushed from the VCO to the VCE. This means, the cloud-init configuration will be overwritten by the VCO after activation.

So I would like to understand if the VCE got activated via the VCO or if it never reached the VCO at the first place - right now, I assume it is not really a cloud-init issue.

**Comment by xiaurrehman143** [comment]
@iddocohen 
Thanks for your response. Yes, I have successfully activated the VCE against the VCO. The cloud-init was working as expected. The issue is that when I turn Off the vEdge and turn On again, the vEdge boot in the default configuration needs to activate again. The same configuration is working fine for the VCG. Turn Off and Turn On the VCG and it is working as expected. I am working on a test lab on EVE-NG/PNETLAB and as we know that EVE-NG/PNETLAB are suing the KVM.

**Comment by iddocohen** [comment]
Thx for the clarification @xiaurrehman143. Could I please ask you to post the cloud-init configuration you are using here?

**Comment by xiaurrehman143** [comment]
[cloud-init.zip](https://github.com/iddocohen/vce_cloudinit/files/8721206/cloud-init.zip)
meta-data:
instance-id: vEdge
local-hostname: vEdge
network-interfaces:
  GE3:
    type: static
    ipaddr: 192.168.100.111
    netmask: 255.255.255.0
    gateway: 192.168.100.240

user-data:
#cloud-config
password: velocloud
chpasswd: { expire: False }
ssh_pwauth: True

runcmd:
  - 'sleep 60'
  - 'sed -i.bak "s/option ignore 1/option ignore 0/" /etc/config/dhcp'
  - '/etc/init.d/network restart'

**Comment by xiaurrehman143** [comment]
Thanks for your response. I pasted the mata and user data with attached cloud-init as well

**Comment by iddocohen** [comment]
Hi @xiaurrehman143 the cloud-init does not look out of the ordinary.

My suggestion thereby is to evaluate with VMware support why after reboot of the VCE the VCE looses its configuration. The issue you have does not sound like a cloud-init topic, which the repository is about but more a "day-2" operation issue hence the suggestion. I will close the issue for now.
